// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RunResult summarises the last successful filter write.
 */
export interface RunResult {
    "filterPath": string;
    "priceSource": string;
    "pricesAtMs": number;
    "thresholdEx": number;
    "divineEx": number;
    "chaosEx": number;
    "valuableCurrency": number;
    "cheapCurrency": number;
    "valuableUniques": number;
    "cheapUniques": number;
    "valuableExcept": number;
    "cheapExcept": number;
}

/**
 * ScanState is the exceptional scanner progress.
 */
export interface ScanState {
    "enabled": boolean;
    "candidates": number;

    /**
     * roughly candidates x 2 (sockets, quality)
     */
    "keys": number;
    "scanned": number;
    "valuable": number;

    /**
     * key waiting for its search
     */
    "current": string;

    /**
     * last finished key and result
     */
    "last": string;
    "nextAtMs": number;

    /**
     * until every base has been scanned once
     */
    "etaSec": number;
}

/**
 * State is everything a front end needs to render.
 */
export interface State {
    "running": boolean;
    "step": string;

    /**
     * 0..1
     */
    "progress": number;
    "lastRunAtMs": number;

    /**
     * 0 when auto update is off
     */
    "nextRunAtMs": number;
    "lastError": string;

    /**
     * LastOkAtMs is when the filter was last written; it stays put when a run
     * fails, so the panel can say the file in the game folder is stale.
     */
    "lastOkAtMs": number;

    /**
     * NextRetryAtMs is the automatic retry after a failed run (0 when none).
     */
    "nextRetryAtMs": number;
    "failCount": number;
    "last": RunResult | null;
    "scan": ScanState;
    "warnings": string[] | null;
    "log": string[] | null;
}
