package filter

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"poe2filter/internal/i18n"
	"poe2filter/internal/prices"
)

// GetPoE2GameDir detects the Path of Exile 2 loot filter folder on Windows.
func GetPoE2GameDir() string {
	userProfile := os.Getenv("USERPROFILE")
	if userProfile == "" {
		return ""
	}
	poe2Path := filepath.Join(userProfile, "Documents", "My Games", "Path of Exile 2")
	if info, err := os.Stat(poe2Path); err == nil && info.IsDir() {
		return poe2Path
	}
	return ""
}

var (
	// A block from an earlier run (only possible with a custom base filter
	// that was itself generated by this tool).
	reOldBlock = regexp.MustCompile(`(?s)#=+\r?\n# \[\[DYNAMIC LOOT FILTER\]\].*?\n# \[\[END DYNAMIC LOOT FILTER\]\]\r?\n`)
	// The first real section header of a NeverSink filter, e.g.
	//   #=====
	//   # [[0100]] Gold
	//   #=====
	// Table-of-contents lines above it are not framed by "#===" lines.
	reFirstSection = regexp.MustCompile(`(?m)^#=+\r?\n# \[\[\d{4}\]\][^\n]*\r?\n#=+`)
)

// Inject places the dynamic block just before NeverSink's first section (so
// after its header and credits, ahead of all its rules), or at the top of an
// unknown base filter.
func Inject(baseContent, block string) string {
	baseContent = reOldBlock.ReplaceAllLiteralString(baseContent, "")
	wrapped := block + "\n# [[END DYNAMIC LOOT FILTER]]\n\n"
	if loc := reFirstSection.FindStringIndex(baseContent); loc != nil {
		// Plain concatenation: the block may contain "$" (NeverSink tags),
		// which regexp replacement would treat as group references.
		return baseContent[:loc[0]] + wrapped + baseContent[loc[0]:]
	}
	return wrapped + baseContent
}

// FilterPath returns where the filter is written in the game folder.
func FilterPath(filterName string) (string, error) {
	dir := GetPoE2GameDir()
	if dir == "" {
		return "", errors.New(i18n.T("err.gameDirLong"))
	}
	return filepath.Join(dir, filterName+".filter"), nil
}

// WriteFilter injects the block into the base filter and writes it to dest.
func WriteFilter(basePath, block, dest string) error {
	base, err := os.ReadFile(basePath)
	if err != nil {
		return fmt.Errorf(i18n.T("err.baseRead"), basePath, err)
	}
	if err := prices.WriteFileAtomic(dest, []byte(Inject(string(base), block))); err != nil {
		return fmt.Errorf(i18n.T("err.filterWrite"), err)
	}
	return nil
}

// LineCount is a small helper for logging.
func LineCount(s string) int { return strings.Count(s, "\n") + 1 }
