// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the API the panel calls. Its methods are exposed to the
 * frontend through generated bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appupdate$0 from "./internal/appupdate/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "./internal/engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as filter$0 from "./internal/filter/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as insights$0 from "./internal/insights/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as overlay$0 from "./internal/overlay/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as trade$0 from "./internal/trade/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddSound copies a sound the user picks into the filter folder, which is the
 * only place the game reads CustomAlertSound files from. It returns the name
 * the file ended up with, or "" if the dialog was cancelled.
 */
export function AddSound(): $CancellablePromise<string> {
    return $Call.ByID(4273186920);
}

/**
 * BrowserLinkState is polled by Settings while a connection is in progress.
 */
export function BrowserLinkState(): $CancellablePromise<$models.BrowserLinkStatus> {
    return $Call.ByID(2730218491);
}

/**
 * CancelBrowserConnect stops waiting for the extension.
 */
export function CancelBrowserConnect(): $CancellablePromise<$models.BrowserLinkStatus> {
    return $Call.ByID(1294041974);
}

/**
 * CheckForAppUpdate checks GitHub Releases now, regardless of the daily timer.
 */
export function CheckForAppUpdate(): $CancellablePromise<appupdate$0.State> {
    return $Call.ByID(899838745);
}

/**
 * ChromiumBrowsers lists the Chromium browsers found through Windows' "App
 * Paths" registration, the default browser marked.
 */
export function ChromiumBrowsers(): $CancellablePromise<$models.ChromiumBrowser[] | null> {
    return $Call.ByID(988412151);
}

export function ClearLiveResults(id: string): $CancellablePromise<trade$0.LiveState[] | null> {
    return $Call.ByID(4277663785, id);
}

/**
 * ConnectBrowser starts (or restarts) a connection: a new code, the local
 * listener, and optionally the default browser on pathofexile.com.
 */
export function ConnectBrowser(openBrowser: boolean): $CancellablePromise<$models.BrowserLinkStatus> {
    return $Call.ByID(1678967024, openBrowser);
}

export function CreateSearchFolder(name: string): $CancellablePromise<overlay$0.SearchLibrary> {
    return $Call.ByID(2940423614, name);
}

export function DeleteOverlaySearch(id: string): $CancellablePromise<overlay$0.SearchLibrary> {
    return $Call.ByID(3425941931, id);
}

/**
 * DeleteProfile removes a profile and switches away from it when it was active.
 */
export function DeleteProfile(name: string): $CancellablePromise<filter$0.Config> {
    return $Call.ByID(1212961758, name);
}

/**
 * DeleteSearchFolder removes a folder and moves its searches to the top level.
 */
export function DeleteSearchFolder(id: string): $CancellablePromise<overlay$0.SearchLibrary> {
    return $Call.ByID(1455352089, id);
}

/**
 * DisconnectBrowser forgets the stored session; searches go out anonymous.
 */
export function DisconnectBrowser(): $CancellablePromise<$models.BrowserLinkStatus> {
    return $Call.ByID(1294868532);
}

/**
 * DownloadAppUpdate downloads and verifies the release executable.
 */
export function DownloadAppUpdate(): $CancellablePromise<appupdate$0.State> {
    return $Call.ByID(2083796200);
}

/**
 * EvaluateOverlay reuses identical successful searches for ten minutes unless
 * refresh is true. In-flight requests are shared as well, so opening Market
 * while the compact overlay is evaluating cannot consume a second GGG search.
 */
export function EvaluateOverlay($in: trade$0.EvaluateRequest, refresh: boolean): $CancellablePromise<trade$0.Evaluation> {
    return $Call.ByID(986547535, $in, refresh);
}

/**
 * ExportFilter saves a copy of the filter that was last written, for sharing or
 * for using it on a machine that does not run this app.
 */
export function ExportFilter(): $CancellablePromise<string> {
    return $Call.ByID(1884601658);
}

/**
 * ExportProfile writes a profile to a file another player can import.
 */
export function ExportProfile(name: string): $CancellablePromise<string> {
    return $Call.ByID(2256871597, name);
}

/**
 * ExportScan asks where to put the scan results and writes them there. It
 * returns the chosen path, or an empty string when the user cancels.
 */
export function ExportScan(): $CancellablePromise<string> {
    return $Call.ByID(4253054929);
}

/**
 * FetchOverlayListings loads the next page of a search the overlay already
 * ran. It uses fetch quota only, so the result list can grow as it scrolls.
 */
export function FetchOverlayListings(searchID: string, ids: string[] | null): $CancellablePromise<trade$0.EvaluatedListing[] | null> {
    return $Call.ByID(1876850263, searchID, ids);
}

/**
 * GetAppUpdateState returns the cached application-update status without doing
 * network work, so opening the settings panel stays instant.
 */
export function GetAppUpdateState(): $CancellablePromise<appupdate$0.State> {
    return $Call.ByID(3665196065);
}

/**
 * GetConfig returns the current settings.
 */
export function GetConfig(): $CancellablePromise<filter$0.Config> {
    return $Call.ByID(3902498144);
}

/**
 * GetMeta returns static app information.
 */
export function GetMeta(): $CancellablePromise<$models.Meta> {
    return $Call.ByID(1638272379);
}

export function GetOverlayDraft(): $CancellablePromise<trade$0.EvaluateRequest> {
    return $Call.ByID(740995069);
}

export function GetOverlaySettings(): $CancellablePromise<overlay$0.Settings> {
    return $Call.ByID(3199014683);
}

export function GetOverlaySnapshot(): $CancellablePromise<overlay$0.Snapshot> {
    return $Call.ByID(2331437714);
}

export function GetSavedOverlaySearches(): $CancellablePromise<overlay$0.SearchLibrary> {
    return $Call.ByID(2510875851);
}

/**
 * GetState returns the current engine state.
 */
export function GetState(): $CancellablePromise<engine$0.State> {
    return $Call.ByID(800887515);
}

export function GetTradeCatalog(): $CancellablePromise<overlay$0.Catalog> {
    return $Call.ByID(1579748955);
}

export function HideMarket(): $CancellablePromise<void> {
    return $Call.ByID(1205462434);
}

export function HideOverlay(): $CancellablePromise<void> {
    return $Call.ByID(4237697434);
}

/**
 * HidePanel hides the tray panel.
 */
export function HidePanel(): $CancellablePromise<void> {
    return $Call.ByID(1659128072);
}

/**
 * ImportProfile adds a profile from a file and switches to it. An empty name
 * means the user cancelled the dialog.
 */
export function ImportProfile(): $CancellablePromise<string> {
    return $Call.ByID(147905064);
}

/**
 * ImportScan asks for a file exported by another player and merges it. A nil
 * result means the user cancelled the dialog.
 */
export function ImportScan(): $CancellablePromise<trade$0.ImportResult | null> {
    return $Call.ByID(3003695854);
}

/**
 * InstallAppUpdate starts the staged updater and exits this process. The
 * updater waits until Windows releases this executable before replacing it.
 */
export function InstallAppUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3476256185);
}

/**
 * Languages lists the interface languages, each named in its own language.
 * The first entry follows the Windows display language.
 */
export function Languages(): $CancellablePromise<$models.LanguageOption[] | null> {
    return $Call.ByID(3617621873);
}

/**
 * Leagues lists the leagues for the picker, live list first, always including
 * the one currently configured.
 */
export function Leagues(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2782642808);
}

/**
 * ListSounds returns the sound files in the PoE2 filter folder, which is where
 * the game looks for CustomAlertSound files.
 */
export function ListSounds(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2994670898);
}

/**
 * LiveResults are a live search's found listings, newest first.
 */
export function LiveResults(id: string): $CancellablePromise<trade$0.EvaluatedListing[] | null> {
    return $Call.ByID(1915515630, id);
}

/**
 * LiveSearches lists the live searches started in this session.
 */
export function LiveSearches(): $CancellablePromise<trade$0.LiveState[] | null> {
    return $Call.ByID(2009755176);
}

/**
 * MoveOverlaySearch puts a saved search into a folder ("" = top level).
 */
export function MoveOverlaySearch(id: string, folder: string): $CancellablePromise<overlay$0.SearchLibrary> {
    return $Call.ByID(3191375457, id, folder);
}

/**
 * NeverSinkThemes lists NeverSink's named styles from the current base filter.
 */
export function NeverSinkThemes(): $CancellablePromise<filter$0.Theme[] | null> {
    return $Call.ByID(3621733729);
}

/**
 * OpenAppUpdatePage opens the trusted GitHub release page in the default
 * browser. Only URLs originating from the fixed GitHub API are accepted.
 */
export function OpenAppUpdatePage(): $CancellablePromise<void> {
    return $Call.ByID(2013235483);
}

/**
 * OpenBrowserExtensionFolder writes the extension out and shows its folder,
 * which is what "Load unpacked" asks for.
 */
export function OpenBrowserExtensionFolder(): $CancellablePromise<string> {
    return $Call.ByID(3006832587);
}

/**
 * OpenDataFolder opens the app's data folder in Explorer.
 */
export function OpenDataFolder(): $CancellablePromise<void> {
    return $Call.ByID(2859855082);
}

/**
 * OpenExtensionsPage opens a browser on its extensions page. A browser only
 * opens its internal pages when started with one, not through a link.
 */
export function OpenExtensionsPage(id: string): $CancellablePromise<void> {
    return $Call.ByID(884454811, id);
}

/**
 * OpenGameFolder opens the PoE2 filter folder in Explorer.
 */
export function OpenGameFolder(): $CancellablePromise<void> {
    return $Call.ByID(1629061476);
}

/**
 * OpenLinkIn opens the pending connection link in a chosen browser, started
 * directly with the link: the extension may live in a browser other than
 * Windows' default, and opening through the default handler failed silently.
 */
export function OpenLinkIn(id: string): $CancellablePromise<void> {
    return $Call.ByID(2250876661, id);
}

export function OpenTradePage(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(1604400219, rawURL);
}

/**
 * OverlayQuota reports how full GGG's search windows are for this IP, so the
 * overlay can show who is spending the quota and why a search waits.
 */
export function OverlayQuota(): $CancellablePromise<trade$0.QuotaStatus> {
    return $Call.ByID(4137594098);
}

/**
 * ParseOverlayText is also useful for diagnostics: a copied item can be pasted
 * into the expanded market without needing to synthesize game input.
 */
export function ParseOverlayText(raw: string): $CancellablePromise<overlay$0.Snapshot> {
    return $Call.ByID(1780103724, raw);
}

/**
 * PrepareBrowserExtension writes the extension into the data folder, where
 * the browser can load it ("Load unpacked"), and returns that folder.
 */
export function PrepareBrowserExtension(): $CancellablePromise<string> {
    return $Call.ByID(1908818204);
}

/**
 * PreviewGameSound plays one of the game's own alert sounds. The sound ships
 * with the app and is written out on first use, since playback needs a path.
 */
export function PreviewGameSound(id: string): $CancellablePromise<void> {
    return $Call.ByID(3037340691, id);
}

/**
 * PreviewOverlay opens the compact window without touching the clipboard. It
 * lets users verify placement and scale from Settings; the latest item remains
 * visible when one has already been captured.
 */
export function PreviewOverlay(): $CancellablePromise<void> {
    return $Call.ByID(2955524718);
}

/**
 * PreviewSound plays a sound file from the filter folder.
 */
export function PreviewSound(name: string): $CancellablePromise<void> {
    return $Call.ByID(3555643989, name);
}

/**
 * Profiles lists the saved settings sets for the picker.
 */
export function Profiles(): $CancellablePromise<engine$0.ProfileInfo[] | null> {
    return $Call.ByID(251923804);
}

/**
 * Quit exits the application.
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2719743713);
}

/**
 * QuoteCurrency prices a stackable item from the filter's price snapshot.
 */
export function QuoteCurrency(name: string): $CancellablePromise<overlay$0.CurrencyQuote> {
    return $Call.ByID(2125667197, name);
}

export function RefreshTradeCatalog(): $CancellablePromise<overlay$0.Catalog> {
    return $Call.ByID(745987832);
}

/**
 * RenameProfile changes a saved profile's name without duplicating it.
 */
export function RenameProfile(oldName: string, newName: string): $CancellablePromise<engine$0.ProfileInfo[] | null> {
    return $Call.ByID(1831808545, oldName, newName);
}

export function RenameSearchFolder(id: string, name: string): $CancellablePromise<overlay$0.SearchLibrary> {
    return $Call.ByID(1110231628, id, name);
}

/**
 * SaveConfig stores new settings and returns them normalised.
 */
export function SaveConfig(c: filter$0.Config): $CancellablePromise<filter$0.Config> {
    return $Call.ByID(2775748437, c);
}

export function SaveOverlaySearch(name: string, folder: string, query: trade$0.EvaluateRequest): $CancellablePromise<overlay$0.SearchLibrary> {
    return $Call.ByID(1440462065, name, folder, query);
}

export function SaveOverlaySettings(next: overlay$0.Settings): $CancellablePromise<overlay$0.Settings> {
    return $Call.ByID(977749632, next);
}

/**
 * SaveProfileAs stores the current settings under a name and makes it active.
 */
export function SaveProfileAs(name: string): $CancellablePromise<engine$0.ProfileInfo[] | null> {
    return $Call.ByID(3887311624, name);
}

/**
 * SearchItems finds uniques, currency and bases for the custom lists.
 */
export function SearchItems(query: string): $CancellablePromise<insights$0.SearchItem[] | null> {
    return $Call.ByID(3116757694, query);
}

/**
 * SetLiveAlerts changes how a live search announces a find, without touching
 * the overlay's shortcuts.
 */
export function SetLiveAlerts(sound: string, notify: boolean): $CancellablePromise<overlay$0.Settings> {
    return $Call.ByID(43895751, sound, notify);
}

export function ShowMarket(): $CancellablePromise<void> {
    return $Call.ByID(1587891371);
}

export function ShowMarketWithQuery($in: trade$0.EvaluateRequest): $CancellablePromise<void> {
    return $Call.ByID(4261131713, $in);
}

/**
 * ShowSettings opens the settings window, on a given section when one is
 * named, and puts the tray panel away: the two are never needed at once.
 */
export function ShowSettings(section: string): $CancellablePromise<void> {
    return $Call.ByID(1323617618, section);
}

/**
 * StartLiveSearch opens a live search for a saved search.
 */
export function StartLiveSearch(id: string): $CancellablePromise<trade$0.LiveState[] | null> {
    return $Call.ByID(1516956964, id);
}

/**
 * StatTiers returns the modifier tier tables of a base, or of an item class
 * when the search names only a category. An empty list means none are known
 * (the tiers could not be built yet, or the item rolls no tiered stats).
 */
export function StatTiers(baseType: string, itemClass: string): $CancellablePromise<overlay$0.TierTable[] | null> {
    return $Call.ByID(500001301, baseType, itemClass);
}

export function StopLiveSearch(id: string): $CancellablePromise<trade$0.LiveState[] | null> {
    return $Call.ByID(2361367652, id);
}

/**
 * StyleGroups lists the drop groups whose colours can be changed.
 */
export function StyleGroups(): $CancellablePromise<filter$0.StyleGroup[] | null> {
    return $Call.ByID(393237167);
}

/**
 * StyleOptions lists the colours and minimap shapes allowed in custom styles.
 */
export function StyleOptions(): $CancellablePromise<$models.StyleOptions> {
    return $Call.ByID(2448222331);
}

/**
 * SwitchProfile loads another profile, applies it and rewrites the filter, so
 * changing what you farm is one click rather than a dozen sliders.
 */
export function SwitchProfile(name: string): $CancellablePromise<filter$0.Config> {
    return $Call.ByID(439236687, name);
}

/**
 * Themes lists the selectable colour palettes.
 */
export function Themes(): $CancellablePromise<filter$0.Theme[] | null> {
    return $Call.ByID(2570218280);
}

/**
 * TradeCurrencies lists the currencies listings are priced in, with icons,
 * without sending the whole stat catalog to a window that only shows prices.
 */
export function TradeCurrencies(): $CancellablePromise<overlay$0.CurrencyEntry[] | null> {
    return $Call.ByID(2565769347);
}

/**
 * TravelToHideout takes the player to the seller's hideout for an instant
 * buyout listing (needs the pathofexile.com session and the game running on
 * the same account).
 */
export function TravelToHideout(token: string): $CancellablePromise<void> {
    return $Call.ByID(1093932661, token);
}

/**
 * UniqueIcons maps unique names to their art, from the last price snapshot
 * (poe.ninja sends an icon with each unique). An unidentified unique shows
 * these so the player can tell the candidates apart by their look.
 */
export function UniqueIcons(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(952393577);
}

/**
 * UpdateNow starts a filter update in the background.
 */
export function UpdateNow(): $CancellablePromise<void> {
    return $Call.ByID(3283441069);
}

/**
 * UserGroupTemplate is the look and sound a new user group starts from, so the
 * panel can render its colour picker like the built-in groups.
 */
export function UserGroupTemplate(): $CancellablePromise<filter$0.StyleGroup> {
    return $Call.ByID(3114360830);
}
