// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the API the panel calls. Its methods are exposed to the
 * frontend through generated bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "./internal/engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as filter$0 from "./internal/filter/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as insights$0 from "./internal/insights/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as trade$0 from "./internal/trade/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportScan asks where to put the scan results and writes them there. It
 * returns the chosen path, or an empty string when the user cancels.
 */
export function ExportScan(): $CancellablePromise<string> {
    return $Call.ByID(4253054929);
}

/**
 * GetConfig returns the current settings.
 */
export function GetConfig(): $CancellablePromise<filter$0.Config> {
    return $Call.ByID(3902498144);
}

/**
 * GetMeta returns static app information.
 */
export function GetMeta(): $CancellablePromise<$models.Meta> {
    return $Call.ByID(1638272379);
}

/**
 * GetState returns the current engine state.
 */
export function GetState(): $CancellablePromise<engine$0.State> {
    return $Call.ByID(800887515);
}

/**
 * HidePanel hides the tray panel.
 */
export function HidePanel(): $CancellablePromise<void> {
    return $Call.ByID(1659128072);
}

/**
 * ImportScan asks for a file exported by another player and merges it. A nil
 * result means the user cancelled the dialog.
 */
export function ImportScan(): $CancellablePromise<trade$0.ImportResult | null> {
    return $Call.ByID(3003695854);
}

/**
 * Languages lists the interface languages, each named in its own language.
 * The first entry follows the Windows display language.
 */
export function Languages(): $CancellablePromise<$models.LanguageOption[] | null> {
    return $Call.ByID(3617621873);
}

/**
 * Leagues lists the leagues for the picker, live list first, always including
 * the one currently configured.
 */
export function Leagues(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2782642808);
}

/**
 * ListSounds returns the sound files in the PoE2 filter folder, which is where
 * the game looks for CustomAlertSound files.
 */
export function ListSounds(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2994670898);
}

/**
 * NeverSinkThemes lists NeverSink's named styles from the current base filter.
 */
export function NeverSinkThemes(): $CancellablePromise<filter$0.Theme[] | null> {
    return $Call.ByID(3621733729);
}

/**
 * OpenDataFolder opens the app's data folder in Explorer.
 */
export function OpenDataFolder(): $CancellablePromise<void> {
    return $Call.ByID(2859855082);
}

/**
 * OpenGameFolder opens the PoE2 filter folder in Explorer.
 */
export function OpenGameFolder(): $CancellablePromise<void> {
    return $Call.ByID(1629061476);
}

/**
 * PreviewSound plays a sound file from the filter folder.
 */
export function PreviewSound(name: string): $CancellablePromise<void> {
    return $Call.ByID(3555643989, name);
}

/**
 * Quit exits the application.
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2719743713);
}

/**
 * SaveConfig stores new settings and returns them normalised.
 */
export function SaveConfig(c: filter$0.Config): $CancellablePromise<filter$0.Config> {
    return $Call.ByID(2775748437, c);
}

/**
 * SearchItems finds uniques, currency and bases for the custom lists.
 */
export function SearchItems(query: string): $CancellablePromise<insights$0.SearchItem[] | null> {
    return $Call.ByID(3116757694, query);
}

/**
 * StyleGroups lists the drop groups whose colours can be changed.
 */
export function StyleGroups(): $CancellablePromise<filter$0.StyleGroup[] | null> {
    return $Call.ByID(393237167);
}

/**
 * StyleOptions lists the colours and minimap shapes allowed in custom styles.
 */
export function StyleOptions(): $CancellablePromise<$models.StyleOptions> {
    return $Call.ByID(2448222331);
}

/**
 * Themes lists the selectable colour palettes.
 */
export function Themes(): $CancellablePromise<filter$0.Theme[] | null> {
    return $Call.ByID(2570218280);
}

/**
 * UpdateNow starts a filter update in the background.
 */
export function UpdateNow(): $CancellablePromise<void> {
    return $Call.ByID(3283441069);
}

/**
 * UserGroupTemplate is the look and sound a new user group starts from, so the
 * panel can render its colour picker like the built-in groups.
 */
export function UserGroupTemplate(): $CancellablePromise<filter$0.StyleGroup> {
    return $Call.ByID(3114360830);
}
