// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface BrowserLinkStatus {
    "state": string;

    /**
     * Connected reports a stored session (the overlay searches signed in).
     */
    "connected": boolean;
    "connectedAt": number;

    /**
     * URL is the link to open by hand in another browser (the code is valid
     * until the request ends).
     */
    "url"?: string;
    "error"?: string;

    /**
     * Rules is GGG's rate-limit policy on the last search ("Account,Ip" when
     * it counted the search as signed in, "Ip" when not; "" before any).
     */
    "rules"?: string;

    /**
     * ExtensionOutdated is set when the extension that answered is older
     * than the one this app carries: its folder has been refreshed, and the
     * browser needs "Reload" on its extensions page to pick it up.
     */
    "extensionOutdated"?: boolean;
}

/**
 * ChromiumBrowser is an installed Chromium-based browser the extension can
 * be loaded into (unpacked, from its extensions page in developer mode).
 */
export interface ChromiumBrowser {
    "id": string;
    "name": string;

    /**
     * Page is the browser's own extensions page ("edge://extensions").
     */
    "page": string;
    "default": boolean;
}

/**
 * LanguageOption is one entry of the language picker.
 */
export interface LanguageOption {
    "id": string;
    "label": string;

    /**
     * Auto marks the entry that follows the Windows display language. Label is
     * the language that choice currently resolves to, Resolved its code.
     */
    "auto": boolean;
    "resolved"?: string;
}

/**
 * Meta is static information for the UI.
 */
export interface Meta {
    "version": string;
    "dataDir": string;
    "gameDir": string;

    /**
     * writing somewhere other than the game folder
     */
    "testMode": boolean;

    /**
     * MaxItemGroups is how many of their own groups a user may keep.
     */
    "maxItemGroups": number;
}

/**
 * StyleOptions are the choices offered in the custom style editor.
 */
export interface StyleOptions {
    "colours": string[] | null;
    "shapes": string[] | null;

    /**
     * group -> NeverSink style tag
     */
    "preset": { [_ in string]?: string } | null;

    /**
     * Sounds are the PlayAlertSound ids, so the panel and the filter writer
     * cannot drift apart about what the game accepts.
     */
    "sounds": string[] | null;
}
