// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Meta is static information for the UI.
 */
export interface Meta {
    "version": string;
    "dataDir": string;
    "gameDir": string;

    /**
     * writing somewhere other than the game folder
     */
    "testMode": boolean;
}

/**
 * StyleOptions are the choices offered in the custom style editor.
 */
export interface StyleOptions {
    "colours": string[] | null;
    "shapes": string[] | null;

    /**
     * group -> NeverSink style tag
     */
    "preset": { [_ in string]?: string } | null;
}
