// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LanguageOption is one entry of the language picker.
 */
export interface LanguageOption {
    "id": string;
    "label": string;

    /**
     * Auto marks the entry that follows the Windows display language. Label is
     * the language that choice currently resolves to, Resolved its code.
     */
    "auto": boolean;
    "resolved"?: string;
}

/**
 * Meta is static information for the UI.
 */
export interface Meta {
    "version": string;
    "dataDir": string;
    "gameDir": string;

    /**
     * writing somewhere other than the game folder
     */
    "testMode": boolean;

    /**
     * MaxItemGroups is how many of their own groups a user may keep.
     */
    "maxItemGroups": number;
}

/**
 * StyleOptions are the choices offered in the custom style editor.
 */
export interface StyleOptions {
    "colours": string[] | null;
    "shapes": string[] | null;

    /**
     * group -> NeverSink style tag
     */
    "preset": { [_ in string]?: string } | null;
}
