// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Config contains all filter generation options matching the GUI settings.
 */
export interface Config {
    /**
     * Value threshold: items worth less are hidden (or dimmed).
     */
    "min_value": number;

    /**
     * "exalted", "chaos", "divine"
     */
    "min_value_unit": string;

    /**
     * "hide", "dim", "show_only"
     */
    "filter_mode": string;
    "include_gear": boolean;
    "t5_rares": boolean;
    "t5_jewels_only": boolean;

    /**
     * 0 = off
     */
    "quality_threshold": number;

    /**
     * mirrors styles["divine"]
     */
    "divine_theme": string;

    /**
     * Styles maps a style group id to a theme id (see StyleGroups).
     */
    "styles": { [_ in string]?: string } | null;
    "divine_sound": string;
    "custom_sound_path": string;
    "hide_exalt": boolean;
    "hide_gold": boolean;
    "filter_name": string;
    "whitelist": string[] | null;
    "blacklist": string[] | null;
    "chance_bases": string[] | null;
    "high_waystones": boolean;
    "high_uncut_gems": boolean;
    "boss_keys_and_tablets": boolean;
    "league_name": string;

    /**
     * Base filter: a NeverSink strictness (0..6), or a custom file when set.
     */
    "strictness": number;
    "custom_base_filter": string;

    /**
     * Exceptional base scanning on the trade API.
     */
    "exceptional_scan": boolean;

    /**
     * share of the IP rate limit, 10..80
     */
    "scan_budget_pct": number;

    /**
     * When set, prices come from this collector server URL first.
     */
    "price_source_url": string;
    "auto_update_enabled": boolean;
    "auto_update_hours": number;
    "notify_enabled": boolean;

    /**
     * Legacy fields, read once for migration and never written back.
     */
    "min_exalt"?: number;
    "min_divine"?: number;
    "base_filter_preset"?: string;
    "auto_update_interval"?: number;
}

/**
 * StyleGroup is a family of highlighted drops whose colours the user can
 * change. Only colours change; size, sound and icon shape stay with the group
 * so the importance ordering of the filter is preserved.
 */
export interface StyleGroup {
    "id": string;
    "label": string;

    /**
     * item name shown in the preview
     */
    "sample": string;
    "defaultLabel": string;

    /**
     * built-in colours
     */
    "default": Theme;
    "allowDefault": boolean;
    "fontSize": number;
    "hasBeam": boolean;

    /**
     * "" when the group has no minimap icon
     */
    "iconShape": string;
}

/**
 * Theme is a colour palette for a highlighted drop. Colours are "R G B A" as
 * the filter language expects; Beam is also used for the minimap icon.
 */
export interface Theme {
    "id": string;
    "label": string;
    "bg": string;
    "text": string;
    "border": string;
    "beam": string;
}
