// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Config contains all filter generation options matching the GUI settings.
 */
export interface Config {
    /**
     * Value threshold: items worth less are hidden (or dimmed).
     */
    "min_value": number;

    /**
     * "exalted", "chaos", "divine"
     */
    "min_value_unit": string;

    /**
     * "hide", "dim", "show_only"
     */
    "filter_mode": string;
    "include_gear": boolean;
    "t5_rares": boolean;
    "t5_jewels_only": boolean;

    /**
     * 0 = off
     */
    "quality_threshold": number;

    /**
     * mirrors styles["divine"]
     */
    "divine_theme": string;

    /**
     * Styles maps a style group id to a theme id (see StyleGroups).
     */
    "styles": { [_ in string]?: string } | null;

    /**
     * CustomStyles holds the user's own look for groups set to "custom".
     */
    "custom_styles": { [_ in string]?: CustomStyle } | null;

    /**
     * legacy, migrated into sounds
     */
    "divine_sound"?: string;

    /**
     * Sounds maps a style group id to a sound choice (see validSound).
     */
    "sounds": { [_ in string]?: string } | null;
    "custom_sound_path": string;
    "hide_exalt": boolean;
    "hide_gold": boolean;
    "filter_name": string;
    "whitelist": string[] | null;

    /**
     * ItemGroups are the user's own lists. Each one shows or hides its items
     * and carries its own colours and sound, keyed by ItemGroup.StyleKey().
     */
    "item_groups": ItemGroup[] | null;
    "chance_bases": string[] | null;
    "high_waystones": boolean;
    "high_uncut_gems": boolean;

    /**
     * Uncut Support Gems drop constantly, so they have their own switch.
     */
    "uncut_support_gems": boolean;
    "boss_keys_and_tablets": boolean;
    "league_name": string;

    /**
     * Base filter: a NeverSink strictness (0..6), or a custom file when set.
     */
    "strictness": number;
    "custom_base_filter": string;

    /**
     * Exceptional base scanning on the trade API.
     */
    "exceptional_scan": boolean;

    /**
     * share of the IP rate limit, 10..80
     */
    "scan_budget_pct": number;

    /**
     * When set, prices come from this collector server URL first.
     */
    "price_source_url": string;

    /**
     * Language is the interface language: "auto" (follow Windows), "tr", "en"
     * or "zh-Hant".
     */
    "language": string;
    "auto_update_enabled": boolean;
    "auto_update_hours": number;
    "notify_enabled": boolean;

    /**
     * Legacy fields, read once for migration and never written back.
     */
    "whitelist_mid"?: string[] | null;
    "blacklist"?: string[] | null;
    "min_exalt"?: number;
    "min_divine"?: number;
    "base_filter_preset"?: string;
    "auto_update_interval"?: number;
}

/**
 * CustomStyle is a user-defined look for one group. Colours are "#rrggbb";
 * empty Beam/Icon/Shape mean "none".
 */
export interface CustomStyle {
    "bg": string;
    "text": string;
    "border": string;
    "beam": string;
    "icon": string;
    "shape": string;
}

/**
 * ItemGroup is one of the user's own item lists. It either shows or hides what
 * it holds, and has its own colours and sound like the built-in groups do.
 */
export interface ItemGroup {
    "id": string;
    "name": string;
    "items": string[] | null;

    /**
     * Hide turns the group into an always-hidden list instead of a shown one.
     */
    "hide": boolean;

    /**
     * Always lets a shown group beat the valuable-item styles. Without it a
     * valuable item keeps its stronger highlight, which is what the medium
     * list has always done.
     */
    "always": boolean;
}

/**
 * StyleGroup is a family of highlighted drops whose colours and sound the
 * user can change. Size and icon shape stay with the group so the importance
 * ordering of the filter is preserved.
 */
export interface StyleGroup {
    "id": string;
    "label": string;

    /**
     * item name shown in the preview
     */
    "sample": string;
    "defaultLabel": string;

    /**
     * built-in colours
     */
    "default": Theme;
    "allowDefault": boolean;

    /**
     * PlayAlertSound id, "" = silent
     */
    "defaultSound": string;
    "fontSize": number;
    "hasBeam": boolean;

    /**
     * "" when the group has no minimap icon
     */
    "iconShape": string;
}

/**
 * Theme is a colour palette for a highlighted drop. Colours are "R G B A" as
 * the filter language expects (empty = the game's default).
 */
export interface Theme {
    "id": string;
    "label": string;
    "bg": string;
    "text": string;
    "border": string;

    /**
     * PlayEffect, e.g. "Red" or "Purple Temp"
     */
    "beam": string;

    /**
     * minimap icon colour; "" = the beam colour
     */
    "icon": string;

    /**
     * minimap icon shape; "" = the group's shape
     */
    "shape": string;

    /**
     * Full themes (NeverSink and custom) apply beam and icon exactly as given,
     * adding or removing them; the built-in palettes only recolour the
     * group's own beam and icon.
     */
    "full": boolean;

    /**
     * NeverSink section, e.g. "currency"
     */
    "category"?: string;

    /**
     * NeverSink rules using this style
     */
    "count"?: number;
}
