// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Status is what the panel shows about the shared prices.
 */
export interface Status {
    "files": number;
    "keys": number;

    /**
     * newest scan among the keys
     */
    "newestMs": number;

    /**
     * last successful look at the release
     */
    "checkedMs": number;
    "league": string;
    "error"?: string;
}
