// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportResult reports what an import changed.
 */
export interface ImportResult {
    "league": string;
    "added": number;
    "updated": number;
    "skipped": number;
}
