// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface EvaluateRequest {
    "league": string;
    "name": string;
    "baseType": string;
    "rarity": string;
    "status": string;
    "stats": SelectedStat[] | null;
    "groups": SelectedStatGroup[] | null;
    "filters": SelectedFilter[] | null;

    /**
     * Sort is a trade sort key ("price", "dps", "stat.explicit.stat_…");
     * empty means price. SortDir is "asc" or "desc".
     */
    "sort"?: string;
    "sortDir"?: string;
}

export interface EvaluatedItem {
    "name": string;
    "baseType": string;
    "rarity": string;
    "itemLevel": number;
    "icon": string;
    "unidentified": boolean;
    "fractured": boolean;
    "corrupted": boolean;

    /**
     * TwiceCorrupted is the trade site's doubleCorrupted flag.
     */
    "twiceCorrupted": boolean;

    /**
     * Mirrored is the trade site's duplicated flag (a Mirror of Kalandra copy).
     */
    "mirrored": boolean;
    "sanctified": boolean;

    /**
     * Sockets counts the augmentable (rune) sockets, filled or empty.
     */
    "sockets": number;

    /**
     * DPS figures are computed from the listing's weapon properties, the same
     * way the trade site shows them; zero for non-weapons.
     */
    "dps": number;
    "physicalDps": number;
    "elementalDps": number;
    "properties": EvaluatedProperty[] | null;
    "mods": EvaluatedMod[] | null;
}

export interface EvaluatedListing {
    "id": string;
    "amount": number;
    "currency": string;
    "account": string;
    "hideoutToken"?: string;
    "listed": string;
    "item": EvaluatedItem;
}

export interface EvaluatedMod {
    "type": string;
    "description": string;
    "name"?: string;
    "tier"?: string;

    /**
     * StatID is the trade stat of this line, so the result list can sort by
     * any affix it shows. Empty when the line matched no stat for certain.
     */
    "statId"?: string;

    /**
     * Parts splits a line that sums several affixes, so each affix shows its
     * own share. GGG sends only the sum and each affix's roll range, so a
     * share is the narrowest range the sum allows, exact when it is pinned.
     */
    "parts"?: EvaluatedModPart[] | null;
}

export interface EvaluatedModPart {
    "name"?: string;
    "tier"?: string;
    "description": string;
}

export interface EvaluatedProperty {
    "name": string;
    "value": string;
}

export interface Evaluation {
    "searchId": string;
    "tradeUrl": string;
    "total": number;

    /**
     * ResultIDs are every listing the search returned (GGG caps it at 100);
     * Listings holds the first page, the rest are fetched as the list scrolls.
     */
    "resultIds": string[] | null;
    "listings": EvaluatedListing[] | null;

    /**
     * SignedIn reports that the search went out with a pathofexile.com
     * session; only then can a listing's hideout travel be used.
     */
    "signedIn": boolean;
}

/**
 * ImportResult reports what an import changed.
 */
export interface ImportResult {
    "league": string;
    "added": number;
    "updated": number;
    "skipped": number;
}

/**
 * LiveState is what the market lists for one live search. ID is the saved
 * search it belongs to.
 */
export interface LiveState {
    "id": string;
    "name": string;
    "status": string;
    "error"?: string;
    "searchId"?: string;
    "tradeUrl"?: string;

    /**
     * Found counts the listings pushed since the search was started.
     */
    "found": number;
    "startedAtMs"?: number;
    "lastFoundMs"?: number;
}

/**
 * QuotaStatus explains the quota for diagnostics: how full each window is,
 * whether GGG restricted the IP, and what the next request would wait for.
 */
export interface QuotaStatus {
    "windows": QuotaWindow[] | null;

    /**
     * zero before the first response
     */
    "observedAt": string;

    /**
     * RestrictedUntil is set while GGG penalises the IP; RestrictedWindowSec
     * names the window that was exceeded (0 when GGG did not say).
     */
    "restrictedUntil": string;
    "restrictedWindowSec": number;
    "waitSec": number;
    "waitReason": string;
    "waitWindowSec": number;

    /**
     * Rules is GGG's last X-Rate-Limit-Rules header; it names "Account" when
     * the request was counted as signed in.
     */
    "rules": string;
}

/**
 * QuotaWindow is one GGG rate-limit window as last seen.
 */
export interface QuotaWindow {
    "periodSec": number;
    "limit": number;

    /**
     * our budgeted share of Limit
     */
    "allowed": number;

    /**
     * estimated current use by everything on this IP
     */
    "hits": number;
    "penaltySec": number;
}

export interface SelectedFilter {
    "group": string;
    "id": string;
    "min"?: number | null;
    "max"?: number | null;
    "option"?: string;

    /**
     * Input is a free-text filter such as the seller account name.
     */
    "input"?: string;
}

export interface SelectedStat {
    "id": string;
    "min"?: number | null;
    "max"?: number | null;
    "weight"?: number | null;
    "disabled"?: boolean;
}

export interface SelectedStatGroup {
    "type": string;
    "min"?: number | null;
    "max"?: number | null;
    "stats": SelectedStat[] | null;
}
