// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface EvaluateRequest {
    "league": string;
    "name": string;
    "baseType": string;
    "rarity": string;
    "status": string;
    "stats": SelectedStat[] | null;
    "groups": SelectedStatGroup[] | null;
    "filters": SelectedFilter[] | null;
}

export interface EvaluatedItem {
    "name": string;
    "baseType": string;
    "rarity": string;
    "itemLevel": number;
    "icon": string;
    "unidentified": boolean;
    "fractured": boolean;
    "corrupted": boolean;
    "sanctified": boolean;

    /**
     * DPS figures are computed from the listing's weapon properties, the same
     * way the trade site shows them; zero for non-weapons.
     */
    "dps": number;
    "physicalDps": number;
    "elementalDps": number;
    "properties": EvaluatedProperty[] | null;
    "mods": EvaluatedMod[] | null;
}

export interface EvaluatedListing {
    "id": string;
    "amount": number;
    "currency": string;
    "account": string;
    "hideoutToken"?: string;
    "listed": string;
    "item": EvaluatedItem;
}

export interface EvaluatedMod {
    "type": string;
    "description": string;
    "name"?: string;
    "tier"?: string;
}

export interface EvaluatedProperty {
    "name": string;
    "value": string;
}

export interface Evaluation {
    "searchId": string;
    "tradeUrl": string;
    "total": number;
    "listings": EvaluatedListing[] | null;
}

/**
 * ImportResult reports what an import changed.
 */
export interface ImportResult {
    "league": string;
    "added": number;
    "updated": number;
    "skipped": number;
}

export interface SelectedFilter {
    "group": string;
    "id": string;
    "min"?: number | null;
    "max"?: number | null;
    "option"?: string;
}

export interface SelectedStat {
    "id": string;
    "min"?: number | null;
    "max"?: number | null;
    "weight"?: number | null;
    "disabled"?: boolean;
}

export interface SelectedStatGroup {
    "type": string;
    "min"?: number | null;
    "stats": SelectedStat[] | null;
}
