// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchItem represents an item or base available for search in custom lists.
 */
export interface SearchItem {
    "name": string;
    "category": string;

    /**
     * "unique", "currency", "base", ...
     */
    "type": string;
    "price_divine"?: number;
    "price_exalt"?: number;
    "base_type"?: string;
    "related_uniques"?: string[] | null;
}
