// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as trade$0 from "../trade/models.js";

/**
 * Catalog is the normalized data the two overlay windows consume. The raw
 * endpoint responses remain on disk so new GGG fields are not destroyed.
 */
export interface Catalog {
    "stats": StatGroup[] | null;
    "items": ItemGroup[] | null;
    "filters": FilterGroup[] | null;

    /**
     * Currencies are the trade site's exchange items by the id listings price
     * in ("divine", "exalted"), with their name and icon.
     */
    "currencies": CurrencyEntry[] | null;
    "updatedAtMs": number;
}

export interface CurrencyEntry {
    "id": string;
    "text": string;
    "image": string;
}

/**
 * CurrencyQuote is what the overlay shows for a stackable item: its value in
 * the price snapshot the filter already uses, so no trade search is needed.
 */
export interface CurrencyQuote {
    "found": boolean;
    "name": string;
    "category": string;
    "valueEx": number;
    "divineEx": number;
    "chaosEx": number;
    "league": string;
    "generatedAt": string;
}

export interface FilterGroup {
    "id": string;
    "title": string;
    "filters": TradeFilter[] | null;
}

export interface FilterInput {
    "placeholder": string;
}

export interface Item {
    "raw": string;
    "class": string;
    "rarity": string;
    "name": string;
    "baseType": string;
    "itemLevel": number;
    "requiredLevel": number;
    "quality": number;

    /**
     * RuneSockets counts the "S" entries of the Sockets line.
     */
    "runeSockets": number;

    /**
     * Exceptional is set when the game prefixed the name with "Exceptional":
     * extra sockets or quality are then what the item is priced by.
     */
    "exceptional": boolean;

    /**
     * StackSize is the count of a stackable item ("Stack Size: 808/5000").
     */
    "stackSize": number;
    "unidentified": boolean;
    "fractured": boolean;
    "corrupted": boolean;

    /**
     * TwiceCorrupted is its own state: a corrupted item corrupted again with
     * another item. It is not also reported as Corrupted.
     */
    "twiceCorrupted": boolean;
    "sanctified": boolean;
    "mirrored": boolean;
    "properties": ItemProperty[] | null;
    "mods": ItemMod[] | null;
}

export interface ItemEntry {
    "type": string;
    "text"?: string;
    "name"?: string;
}

export interface ItemGroup {
    "id": string;
    "label": string;
    "entries": ItemEntry[] | null;
}

export interface ItemMod {
    "key": string;
    "statId": string;
    "text": string;
    "type": string;
    "affix": string;
    "name": string;
    "tier": number;
    "values": number[] | null;
    "selected": boolean;

    /**
     * Tiers lists each affix's tier when several affixes of the same stat
     * were merged into this line ("P1+P1"); empty for a single affix.
     */
    "tiers"?: number[] | null;

    /**
     * AltStatIDs are catalog stats with the same wording as StatID (a local
     * or global twin); searches accept any of them through a count group.
     */
    "altStatIds"?: string[] | null;
}

export interface ItemProperty {
    "name": string;
    "value": string;
}

export interface SavedSearch {
    "id": string;
    "name": string;
    "query": trade$0.EvaluateRequest;
    "createdAt": string;
}

export interface SelectOption {
    "id": string;
    "text": string;
}

/**
 * Settings are stored in overlay.json next to config.json.
 */
export interface Settings {
    "enabled": boolean;
    "hotkey": string;
    "auto_scale": boolean;
    "ui_scale": number;
}

/**
 * Snapshot is kept by the service so windows opened after the hotkey event can
 * still render the latest item (or the capture error that explains why not).
 */
export interface Snapshot {
    "item"?: Item | null;
    "error"?: string;
}

export interface StatEntry {
    "id": string;
    "text": string;
    "type": string;
}

export interface StatGroup {
    "id": string;
    "label": string;
    "entries": StatEntry[] | null;
}

export interface TradeFilter {
    "id": string;
    "text": string;
    "minMax": boolean;
    "option": optionList;

    /**
     * Input is set for free-text filters (the seller account name).
     */
    "input"?: FilterInput | null;
}

export interface optionList {
    "options": SelectOption[] | null;
}
