// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as trade$0 from "../trade/models.js";

/**
 * Catalog is the normalized data the two overlay windows consume. The raw
 * endpoint responses remain on disk so new GGG fields are not destroyed.
 */
export interface Catalog {
    "stats": StatGroup[] | null;
    "items": ItemGroup[] | null;
    "filters": FilterGroup[] | null;
    "updatedAtMs": number;
}

export interface FilterGroup {
    "id": string;
    "title": string;
    "filters": TradeFilter[] | null;
}

export interface Item {
    "raw": string;
    "class": string;
    "rarity": string;
    "name": string;
    "baseType": string;
    "itemLevel": number;
    "requiredLevel": number;
    "quality": number;

    /**
     * RuneSockets counts the "S" entries of the Sockets line.
     */
    "runeSockets": number;
    "unidentified": boolean;
    "fractured": boolean;
    "corrupted": boolean;

    /**
     * TwiceCorrupted is its own state: a corrupted item corrupted again with
     * another item. It is not also reported as Corrupted.
     */
    "twiceCorrupted": boolean;
    "sanctified": boolean;
    "mirrored": boolean;
    "properties": ItemProperty[] | null;
    "mods": ItemMod[] | null;
}

export interface ItemEntry {
    "type": string;
    "text"?: string;
    "name"?: string;
}

export interface ItemGroup {
    "id": string;
    "label": string;
    "entries": ItemEntry[] | null;
}

export interface ItemMod {
    "key": string;
    "statId": string;
    "text": string;
    "type": string;
    "affix": string;
    "name": string;
    "tier": number;
    "values": number[] | null;
    "selected": boolean;
}

export interface ItemProperty {
    "name": string;
    "value": string;
}

export interface SavedSearch {
    "id": string;
    "name": string;
    "query": trade$0.EvaluateRequest;
    "createdAt": string;
}

export interface SelectOption {
    "id": string;
    "text": string;
}

/**
 * Settings are stored in overlay.json next to config.json.
 */
export interface Settings {
    "enabled": boolean;
    "hotkey": string;
    "auto_scale": boolean;
    "ui_scale": number;
}

/**
 * Snapshot is kept by the service so windows opened after the hotkey event can
 * still render the latest item (or the capture error that explains why not).
 */
export interface Snapshot {
    "item"?: Item | null;
    "error"?: string;
}

export interface StatEntry {
    "id": string;
    "text": string;
    "type": string;
}

export interface StatGroup {
    "id": string;
    "label": string;
    "entries": StatEntry[] | null;
}

export interface TradeFilter {
    "id": string;
    "text": string;
    "minMax": boolean;
    "option": optionList;
}

export interface optionList {
    "options": SelectOption[] | null;
}
