// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * State is the application-update status exposed to the panel.
 */
export interface State {
    "status": string;
    "currentVersion": string;
    "latestVersion"?: string;
    "releaseUrl"?: string;
    "progress"?: number;
    "error"?: string;
    "canInstall": boolean;
    "checkedAtMs"?: number;
}
